// Converts a StudyPlan response into clean, shareable Markdown.

export function planToMarkdown(plan) {
  if (!plan) return "";

  const lines = [];
  const meta = plan.generation_metadata || {};

  // ── Header ────────────────────────────────────────────────────────────────
  lines.push(`# 🎓 Study Plan`);
  lines.push("");
  lines.push(`**Goal:** ${plan.goal}`);
  const stats = [];
  if (plan.gap_analysis?.gaps) stats.push(`${plan.gap_analysis.gaps.length} gaps`);
  if (plan.milestone_plan?.milestones)
    stats.push(`${plan.milestone_plan.milestones.length} weeks`);
  if (meta.elapsed_seconds != null) stats.push(`built in ${meta.elapsed_seconds}s`);
  if (stats.length) lines.push(`*${stats.join(" · ")}*`);
  lines.push("");

  // ── Verification ──────────────────────────────────────────────────────────
  const v = plan.verification;
  if (v) {
    const icon = v.status === "approved" ? "✅" : "⚠️";
    lines.push(`> ${icon} **Verification:** ${v.status}`);
    if (v.reasoning) lines.push(`>`, `> ${v.reasoning}`);
    if (v.issues?.length) {
      lines.push(`>`);
      v.issues.forEach((i) => lines.push(`> - ${i}`));
    }
    lines.push("");
  }

  // ── Gaps ──────────────────────────────────────────────────────────────────
  const gaps = plan.gap_analysis?.gaps || [];
  if (gaps.length) {
    lines.push(`## 🔍 Knowledge Gaps`);
    lines.push("");
    gaps.forEach((g) => {
      lines.push(`### ${g.concept} _(${g.severity} priority)_`);
      if (g.evidence) lines.push(`- **Evidence:** ${g.evidence}`);
      if (g.prerequisite_for?.length)
        lines.push(`- **Unlocks:** ${g.prerequisite_for.join(", ")}`);
      lines.push("");
    });
  }

  // ── Milestones ────────────────────────────────────────────────────────────
  const milestones = plan.milestone_plan?.milestones || [];
  if (milestones.length) {
    lines.push(`## 🗺️ Week-by-Week Plan`);
    lines.push("");
    milestones.forEach((m) => {
      lines.push(`### Week ${m.week} — ${m.title}`);
      if (m.closes_gaps?.length)
        lines.push(`*Closes: ${m.closes_gaps.join(", ")}*`);
      lines.push("");
      (m.objectives || []).forEach((o) => lines.push(`- [ ] ${o}`));
      if (m.reasoning) {
        lines.push("");
        lines.push(`> 💭 ${m.reasoning}`);
      }
      lines.push("");
    });

    const adjustments = plan.milestone_plan?.adjustments_made || [];
    if (adjustments.length) {
      lines.push(`**Pacing adjustments:**`);
      adjustments.forEach((a) => lines.push(`- ${a}`));
      lines.push("");
    }
  }

  // ── Resources ─────────────────────────────────────────────────────────────
  const byGap = plan.resources?.by_gap || {};
  if (Object.keys(byGap).length) {
    lines.push(`## 📚 Curated Resources`);
    lines.push("");
    Object.entries(byGap).forEach(([concept, resources]) => {
      lines.push(`### ${concept}`);
      resources.forEach((r) => {
        lines.push(
          `- [${r.title}](${r.url}) — _${r.resource_type}, ~${r.estimated_hours}h_`
        );
        if (r.relevance_reason) lines.push(`  - ${r.relevance_reason}`);
      });
      lines.push("");
    });
  }

  // ── Reasoning trace ───────────────────────────────────────────────────────
  const trace = plan.reasoning_trace || [];
  if (trace.length) {
    lines.push(`## 🧠 How ${trace.length} Agents Reasoned This`);
    lines.push("");
    trace.forEach((t) => {
      lines.push(`**${t.step}. ${t.agent}** — ${t.role}`);
      lines.push(`- ${t.summary}`);
      if (t.reasoning) lines.push(`- _${t.reasoning}_`);
      lines.push("");
    });
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push(
    `_Generated by CurriculumMind on ${meta.framework || "Microsoft Agent Framework"}_`
  );

  return lines.join("\n");
}
